carsapp/config/routes.rb
Rails.application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :cars
      resources :drivers
      resources :driver_cars
    end
  end
end

carsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carsapp/app/models/car.rb
class Car < ApplicationRecord
    # define assosiation between cars and drivers
    has_many :driver_cars
    has_many :drivers, through: :driver_cars
end

carsapp/app/models/driver.rb
class Driver < ApplicationRecord
    has_many :driver_cars
    has_many :cars, through: :driver_cars
end

carsapp/app/models/driver_car.rb
class DriverCar < ApplicationRecord
  belongs_to :driver
  belongs_to :car
end

carsapp/app/controllers/api/v1/cars_controller.rb
module Api
    module V1
        class CarsController < ApplicationController
            def index 
                cars = Car.includes(:drivers)
                render :json => cars.to_json( :include => [:drivers] ), status: :ok
            end
            
            def show
                car = Car.includes(:drivers).find(params[:id])
                render :json => car.to_json( :include => [:drivers] ), status: :ok
            end

            def create
                car = Car.new(car_params)
                car.save
                render json:car, status: :created
            end

            private
            def car_params
                params.require(:car).permit(:name, :img , :type , :color)
            end
        end
    end
end

carsapp/app/controllers/api/v1/driver_cars_controller.rb
module Api
    module V1
        class DriverCarsController < ApplicationController
            def index 
                driver_cars = DriverCar.all()
                render :json => driver_cars, status: :ok
            end
            
            def show
                driver_car = DriverCar.find(params[:id])
                render :json => driver_car, status: :ok
            end

            def create
                driverCarArr = []
                for driver in params[:driver_id] do
                   for car in params[:car_id] do
                        model = {
                            driver_id: driver,
                            car_id: car
                        }
                        
                        driverCarArr << model
                    end
                end
                
                DriverCar.create(driverCarArr)
                
                head :no_content

            end
        end
    end
end

carsapp/app/controllers/api/v1/drivers_controller.rb
module Api
    module V1
        class DriversController < ApplicationController
            def index 
                drivers = Driver.includes(:cars)
                render :json => drivers.to_json( :include => [:cars] ), status: :ok
            end
            
            def show
                drivers = Driver.includes(:cars).find(params[:id])
                render :json => drivers.to_json( :include => [:cars] ), status: :ok
            end

            def create
                driver = Driver.new(driver_params)
                driver.save
                render json:driver, status: :created
            end

            private
            def driver_params
                params.require(:driver).permit(:name , :email)
            end
        end
    end
end

carsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

carsapp/app/helpers/api/v1/driver_car_helper.rb
module Api::V1::DriverCarHelper
end

carsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

carsapp/app/helpers/car_helper.rb
module CarHelper
end

carsapp/app/helpers/driver_car_helper.rb
module DriverCarHelper
end

carsapp/app/helpers/driver_cars_helper.rb
module DriverCarsHelper
end

carsapp/app/helpers/driver_helper.rb
module DriverHelper
end

carsapp/app/helpers/drivers_helper.rb
module DriversHelper
end

carsapp/app/views/driver_cars/_form.html.erb
<%= form_with(model: driver_car) do |form| %>
  <% if driver_car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver_car.errors.count, "error") %> prohibited this driver_car from being saved:</h2>

      <ul>
        <% driver_car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :driver_id %>
    <%= form.text_field :driver_id %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.text_field :car_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

carsapp/app/views/driver_cars/edit.html.erb
<h1>Editing Driver Car</h1>

<%= render 'form', driver_car: @driver_car %>

<%= link_to 'Show', @driver_car %> |
<%= link_to 'Back', driver_cars_path %>

carsapp/app/views/driver_cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Driver Cars</h1>

<table>
  <thead>
    <tr>
      <th>Driver</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @driver_cars.each do |driver_car| %>
      <tr>
        <td><%= driver_car.driver_id %></td>
        <td><%= driver_car.car_id %></td>
        <td><%= link_to 'Show', driver_car %></td>
        <td><%= link_to 'Edit', edit_driver_car_path(driver_car) %></td>
        <td><%= link_to 'Destroy', driver_car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver Car', new_driver_car_path %>

carsapp/app/views/driver_cars/new.html.erb
<h1>New Driver Car</h1>

<%= render 'form', driver_car: @driver_car %>

<%= link_to 'Back', driver_cars_path %>

carsapp/app/views/driver_cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driver:</strong>
  <%= @driver_car.driver_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @driver_car.car_id %>
</p>

<%= link_to 'Edit', edit_driver_car_path(@driver_car) %> |
<%= link_to 'Back', driver_cars_path %>

carsapp/app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

carsapp/app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

carsapp/app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

carsapp/app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

carsapp/app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

carsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>